# Watchlist managed from the Stock Guru app. Edit here or in the app.

[[stocks]]
symbol = "OCTOPUS"
name = "Octopus Digital"
sector = "0828"

[[stocks]]
symbol = "AVN"
name = "Avanceon Ltd"
sector = "0828"

[[stocks]]
symbol = "TREET"
name = "Treet Corp"
sector = "0810"

[[stocks]]
symbol = "FCL"
name = "Fast Cables Ltd."
sector = "0803"

[[stocks]]
symbol = "WAVESAPP"
name = "Waves Home App"
sector = "0803"

[[stocks]]
symbol = "WAVES"
name = "Waves Corp Ltd."
sector = "0803"

[[stocks]]
symbol = "FATIMA"
name = "Fatima Fert"
sector = "0809"

[[stocks]]
symbol = "FFC"
name = "Fauji Fert"
sector = "0809"

[[stocks]]
symbol = "CNERGY"
name = "Cnergyico PK"
sector = "0825"

[[stocks]]
symbol = "HUBC"
name = "Hub Power Co."
sector = "0824"
