"""App bundle: everything the phone app shows, as static JSON + PNG under data/app/.

    summary.json            as_of, watchlist, per-stock snapshot (daily performance, trend)
    stocks/<SYM>.json       detail: snapshot, sentences, patterns, setups+base rates, outlook,
                            longterm, fundamentals, corporate (AGM, ex-dividend), history (250 rows)
    history/<SYM>.json      full OHLCV history (all available sessions)
    charts/<SYM>.png        annotated chart for as_of
    symbols.json            every equity with a last close (for the watchlist picker)
    scorecard.json          self-scoring summary

Regenerated by `python -m stockbot export` (and by `run`)."""
from __future__ import annotations

import json
import shutil
from dataclasses import asdict
from datetime import date
from pathlib import Path

from stockbot import corporate, scoring
from stockbot.analysis import daily as daily_analysis, longterm, outlook
from stockbot.config import Settings
from stockbot.storage.db import DB


def _clean(o):
    """JSON-safe: NaN/inf -> None."""
    if isinstance(o, float) and (o != o or o in (float("inf"), float("-inf"))):
        return None
    if isinstance(o, dict):
        return {k: _clean(v) for k, v in o.items()}
    if isinstance(o, (list, tuple)):
        return [_clean(v) for v in o]
    return o


def _dump(path: Path, obj) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(_clean(obj), separators=(",", ":")), encoding="utf-8")


def symbols(db: DB, as_of: str) -> list[dict]:
    rows = db.conn.execute(
        "SELECT e.symbol, e.name, e.sector_code, e.close FROM eod e JOIN (SELECT symbol, MAX(date) d FROM eod WHERE date<=? GROUP BY symbol) m "
        "ON e.symbol=m.symbol AND e.date=m.d WHERE e.sector_code GLOB '08[0-9][0-9]' AND e.close>0 ORDER BY e.symbol", (as_of,)).fetchall()
    import re
    out = []
    for r in rows:
        name = re.sub(r"(XD|XB|XR)+$", "", r["name"] or "").strip()
        out.append({"symbol": r["symbol"], "name": name, "sector_code": r["sector_code"], "close": r["close"]})
    return out


def build(db: DB, cfg: Settings, as_of: date, analysis: daily_analysis.DailyAnalysis | None = None,
          charts: dict[str, Path] | None = None) -> Path:
    out = cfg.data_dir / "app"
    iso = as_of.isoformat()
    analysis = analysis or daily_analysis.build(db, cfg, as_of)
    stocks_summary = []
    for s in analysis.snapshots:
        snap = asdict(s)
        comp = db.company(s.symbol, iso)
        corp = corporate.summary(db, s.symbol, iso)
        ps = longterm.price_stats(db, s.symbol, iso)
        fv = longterm.fundamentals_view(comp, s.close)
        hist = db.history(s.symbol, iso, 10_000)
        hist_rows = [{"d": r["date"], "o": r["open"], "h": r["high"], "l": r["low"], "c": r["close"], "v": r["volume"]} for r in hist]
        detail = {
            "as_of": iso,
            "snapshot": snap,
            "outlook": outlook.build(db, s, iso) if s.ok else None,
            "longterm": {"price": ps, "fundamentals": fv, "sentences": longterm.sentences(s.symbol, ps, fv, corp)},
            "corporate": {
                **corp,
                "agm_date": comp.get("agm_date") if comp else None,
                "agm_notice": comp.get("agm_notice") if comp else None,
                "latest_result": comp.get("latest_result") if comp else None,
                "latest_board_meeting": comp.get("latest_board_meeting") if comp else None,
                "announcements": (comp.get("announcements") or [])[:15] if comp else [],
                "fiscal_year_end": comp.get("fiscal_year_end") if comp else None,
                "company_name": comp.get("name") if comp else s.name,
                "sector": comp.get("sector") if comp else s.sector,
                "business": comp.get("business") if comp else "",
                "source": "https://dps.psx.com.pk/company/" + s.symbol,
            },
            "history_recent": hist_rows[-250:],
            "chart": f"charts/{s.symbol}.png" if charts and s.symbol in charts else None,
        }
        _dump(out / "stocks" / f"{s.symbol}.json", detail)
        _dump(out / "history" / f"{s.symbol}.json", {"symbol": s.symbol, "rows": hist_rows})
        if charts and s.symbol in charts and charts[s.symbol].exists():
            (out / "charts").mkdir(parents=True, exist_ok=True)
            shutil.copyfile(charts[s.symbol], out / "charts" / f"{s.symbol}.png")
        stocks_summary.append({
            "symbol": s.symbol, "name": s.name, "sector": s.sector, "ok": s.ok, "close": s.close, "change_pct": s.change_pct,
            "volume_ratio": s.volume_ratio, "rsi": s.rsi, "trend": s.trend, "ret_1w": s.ret_1w, "ret_1m": s.ret_1m, "ret_3m": s.ret_3m,
            "off_high_pct": s.off_high_pct, "setups": [b["label"] for b in s.base_rates], "patterns": [p["label"] for p in s.patterns],
            "problems": s.problems, "agm_date": comp.get("agm_date") if comp else None, "last_ex_dividend": corp.get("last_ex_dividend"),
            "declared_dividend_ps": (corp["upcoming"][0]["dividend_per_share"] if corp.get("upcoming") else (corp["last_dividend"]["dividend_per_share"] if corp.get("last_dividend") else None)),
            "next_book_closure": corp["upcoming"][0]["bc_from"] if corp.get("upcoming") else None,
        })
    outs = scoring.outcomes(db, iso)
    _dump(out / "summary.json", {
        "as_of": iso, "generated_at": __import__("datetime").datetime.now().isoformat(timespec="seconds"),
        "data_ok": analysis.data_ok, "data_problems": analysis.data_problems,
        "watchlist": [{"symbol": st.symbol, "name": st.name, "sector": st.sector} for st in cfg.watchlist],
        "stocks": stocks_summary,
        "holdings": analysis.holdings,
        "disclaimer": "Personal research tool. Describes data and history only; no advice, no forecasts.",
    })
    _dump(out / "scorecard.json", {"as_of": iso, "markdown": scoring.scorecard_markdown(outs, iso), "n_signals": len(outs)})
    _dump(out / "symbols.json", {"as_of": iso, "symbols": symbols(db, iso)})
    return out
